name: Store SBOM Data for ingestion into 'https://sbom.eclipse.org'

on:
  workflow_call:
    inputs:
      projectName:
        description: 'The project name associated with the uploaded SBOM.'
        type: string
        required: true
      projectVersion:
        description: 'The version associated with the uploaded SBOM.'
        type: string
        required: true
      bomArtifact:
        description: 'The artifact name where the SBOM is uploaded to.'
        type: string
        required: true
        default: 'sbom'
      bomFilename:
        description: 'The filename of the generated SBOM within the bomArtifact.'
        type: string
        required: true
      parentProject:
        description: 'The parent project UUID the upload SBOM should be associated with.'
        type: string
        required: true

jobs:
  store-sbom-data:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: "Download sbom"
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ inputs.bomArtifact }}
      - name: "Generate metadata"
        shell: bash
        run: |
          if [ -z "${{ inputs.projectName }}" ]; then
            echo "projectName is empty"
            exit 1
          fi

          if [ -z "${{ inputs.projectVersion }}" ]; then
            echo "projectVersion is empty"
            exit 1
          fi

          if [ -z "${{ inputs.parentProject }}" ]; then
            echo "parentProject is empty"
            exit 1
          fi
          
          echo "$(cat <<EOT
          {
            "projectName": "${{ inputs.projectName }}",
            "projectVersion": "${{ inputs.projectVersion }}",
            "parentProject": "${{ inputs.parentProject }}"
          }
          EOT
          )" > metadata.json

          if [ ! -f ${{ inputs.bomFilename }} ]; then
            echo "Input bom file not found!"
            exit 1
          fi

          if [[ "${{ inputs.bomFilename }}" != "bom.json" ]]; then 
            cp ${{ inputs.bomFilename }} bom.json
          fi

      - name: Upload sbom metadata
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: eclipse-sbom-data
          path: |
            bom.json
            metadata.json
